name: pizza_counter
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  back_button_interceptor: ^7.0.3
  flag: ^7.0.0
  path: ^1.8.3
  path_provider: ^2.1.2
  sqflite: ^2.3.2
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  generate: true

  assets:
    - assets/images/
